version: '2'
services:
    proyectonuevo-app:
        image: proyectonuevo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://proyectonuevo-mysql:3306/proyectonuevo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proyectonuevo-mysql:
        extends:
            file: mysql.yml
            service: proyectonuevo-mysql
